apiVersion: v1
kind: Service
metadata:
  name: fleetman-webapp

spec:
  # this defines which pods are going to be represented by this service
  # this service becomes a network endpoint for either other services
  # or may be external users to connect to (eg Browser)
  selector:
    app: webapp
    release: "0-5"

  ports:
    - name: http
      port: 80
      nodePort: 30080

  type: NodePort

--- # new document
apiVersion: v1
kind: Service
metadata:
  name: fleetman-queue

spec:
  # this defines which pods are going to be represented by this service
  # this service becomes a network endpoint for either other services
  # or may be external users to connect to (eg Browser)
  selector:
    app: webapp

  ports:
    - name: http
      port: 8161
      nodePort: 30010 # expose to out site world from cluster

    - name: endpoint
      port: 61616

  type: NodePort
